### ISSUE TITLE
Additional python package requirements

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/AutoTransformPy#28]
Checklist of requirements to update python package:  
  - [x] Ensure software license is selected  
  - [X] Add additional test cases for `rotate` function  
  - [X] Add additional test cases for `mirror` function  
  - [X] Add additional test cases for `translate` function  
  - [X] Update documentation, if required

**Comment by alyciakb** [comment]
Test that  file path passed into functions leads to an actual file:
- [X] Add `FileNotFound` error to `rotate` function test suite
- [x] Add `FileNotFound` error to `translate` function test suite
